FROM oven/bun:1

RUN apt-get update && \
	apt-get install -y ffmpeg && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /repo

COPY package.json bun.lock ./
COPY apps ./apps
COPY packages ./packages
COPY services ./services

WORKDIR /repo/services/worker
RUN bun install --production --frozen-lockfile
CMD ["bun", "start"]
